on:
  push:
    branches:
      - main

jobs:
  check_for_updated_json:
    runs-on: ubuntu-latest
    name: Check for sample.json updates
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 2
      - name: Get changes
        id: changed-files
        run: echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
      - name: List changed files
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}
            echo "$file was changed"
          done

